#!/bin/bash
# Quick Commands Reference

echo "════════════════════════════════════════════════════"
echo "🚀 NYC TAXI PIPELINE - QUICK COMMANDS"
echo "════════════════════════════════════════════════════"
echo ""
echo "📊 VIEW DASHBOARD:"
echo "   open data/output/dashboard_advanced_202401.html"
echo ""
echo "📤 PUSH TO GITHUB:"
echo "   ./push_to_github.sh"
echo ""
echo "🔄 RUN PIPELINE:"
echo "   python src/pipeline/main_pipeline.py"
echo ""
echo "📝 VIEW METRICS:"
echo "   cat data/output/metrics_202401.csv"
echo ""
echo "📋 VIEW LOGS:"
echo "   tail -50 logs/pipeline_*.log"
echo ""
echo "🎥 RECORD VIDEO:"
echo "   1. Read: LOOM_VIDEO_GUIDE.md"
echo "   2. Sign up: https://www.loom.com"
echo "   3. Record 3-5 minutes"
echo ""
echo "════════════════════════════════════════════════════"
